<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => ['en' => 'Afghanistan', 'mk' => 'Авганистан']],
            ['name' => ['en' => 'Aland Islands', 'mk' => 'Оландски Острови']],
            ['name' => ['en' => 'Albania', 'mk' => 'Албанија']],
            ['name' => ['en' => 'Algeria', 'mk' => 'Алжир']],
            ['name' => ['en' => 'American Samoa', 'mk' => 'Американска Самоа']],
            ['name' => ['en' => 'Andorra', 'mk' => 'Андора']],
            ['name' => ['en' => 'Angola', 'mk' => 'Ангола']],
            ['name' => ['en' => 'Anguilla', 'mk' => 'Ангвила']],
            ['name' => ['en' => 'Antarctica', 'mk' => 'Антарктик']],
            ['name' => ['en' => 'Antigua and Barbuda', 'mk' => 'Антигва и Барбуда']],
            ['name' => ['en' => 'Argentina', 'mk' => 'Аргентина']],
            ['name' => ['en' => 'Armenia', 'mk' => 'Ерменија']],
            ['name' => ['en' => 'Aruba', 'mk' => 'Аруба']],
            ['name' => ['en' => 'Australia', 'mk' => 'Австралија']],
            ['name' => ['en' => 'Austria', 'mk' => 'Австрија']],
            ['name' => ['en' => 'Azerbaijan', 'mk' => 'Азербејџан']],
            ['name' => ['en' => 'Bahamas', 'mk' => 'Бахами']],
            ['name' => ['en' => 'Bahrain', 'mk' => 'Бахреин']],
            ['name' => ['en' => 'Bangladesh', 'mk' => 'Бангладеш']],
            ['name' => ['en' => 'Barbados', 'mk' => 'Барбадос']],
            ['name' => ['en' => 'Belarus', 'mk' => 'Белорусија']],
            ['name' => ['en' => 'Belgium', 'mk' => 'Белгија']],
            ['name' => ['en' => 'Belize', 'mk' => 'Белизе']],
            ['name' => ['en' => 'Benin', 'mk' => 'Бенин']],
            ['name' => ['en' => 'Bermuda', 'mk' => 'Бермуди']],
            ['name' => ['en' => 'Bhutan', 'mk' => 'Бутан']],
            ['name' => ['en' => 'Bolivia, Plurinational State of', 'mk' => 'Боливија, Множинска Држава']],
            ['name' => ['en' => 'Bosnia and Herzegovina', 'mk' => 'Босна и Херцеговина']],
            ['name' => ['en' => 'Botswana', 'mk' => 'Боцвана']],
            ['name' => ['en' => 'Brazil', 'mk' => 'Бразил']],
            ['name' => ['en' => 'British Indian Ocean Territory', 'mk' => 'Британска Индиска Океанска Територија']],
            ['name' => ['en' => 'Brunei Darussalam', 'mk' => 'Брунеј Дарусалам']],
            ['name' => ['en' => 'Bulgaria', 'mk' => 'Бугарија']],
            ['name' => ['en' => 'Burkina Faso', 'mk' => 'Буркина Фасо']],
            ['name' => ['en' => 'Burundi', 'mk' => 'Бурунди']],
            ['name' => ['en' => 'Cambodia', 'mk' => 'Камбоџа']],
            ['name' => ['en' => 'Cameroon', 'mk' => 'Камерун']],
            ['name' => ['en' => 'Canada', 'mk' => 'Канада']],
            ['name' => ['en' => 'Cape Verde', 'mk' => 'Зелен ’Рт']],
            ['name' => ['en' => 'Cayman Islands', 'mk' => 'Кајмански Острови']],
            ['name' => ['en' => 'Central African Republic', 'mk' => 'Централноафриканска Република']],
            ['name' => ['en' => 'Chad', 'mk' => 'Чад']],
            ['name' => ['en' => 'Chile', 'mk' => 'Чиле']],
            ['name' => ['en' => 'China', 'mk' => 'Кина']],
            ['name' => ['en' => 'Christmas Island', 'mk' => 'Божиќен Остров']],
            ['name' => ['en' => 'Cocos (Keeling) Islands', 'mk' => 'Кокосови (Килинг) Острови']],
            ['name' => ['en' => 'Colombia', 'mk' => 'Колумбија']],
            ['name' => ['en' => 'Comoros', 'mk' => 'Коморски Острови']],
            ['name' => ['en' => 'Congo', 'mk' => 'Конго']],
            ['name' => ['en' => 'Congo, The Democratic Republic of the Congo', 'mk' => 'Конго, Демократска Република Конго']],
            ['name' => ['en' => 'Cook Islands', 'mk' => 'Острови на Кук']],
            ['name' => ['en' => 'Costa Rica', 'mk' => 'Коста Рика']],
            ['name' => ['en' => 'Cote dIvoire', 'mk' => 'Брегот на Слоновата Коска']],
            ['name' => ['en' => 'Croatia', 'mk' => 'Хрватска']],
            ['name' => ['en' => 'Cuba', 'mk' => 'Куба']],
            ['name' => ['en' => 'Cyprus', 'mk' => 'Кипар']],
            ['name' => ['en' => 'Czech Republic', 'mk' => 'Чешка']],
            ['name' => ['en' => 'Denmark', 'mk' => 'Данска']],
            ['name' => ['en' => 'Djibouti', 'mk' => 'Џибути']],
            ['name' => ['en' => 'Dominica', 'mk' => 'Доминика']],
            ['name' => ['en' => 'Dominican Republic', 'mk' => 'Доминиканска Република']],
            ['name' => ['en' => 'Ecuador', 'mk' => 'Еквадор']],
            ['name' => ['en' => 'Egypt', 'mk' => 'Египет']],
            ['name' => ['en' => 'El Salvador', 'mk' => 'Ел Салвадор']],
            ['name' => ['en' => 'Equatorial Guinea', 'mk' => 'Екваторска Гвинеја']],
            ['name' => ['en' => 'Eritrea', 'mk' => 'Еритреја']],
            ['name' => ['en' => 'Estonia', 'mk' => 'Естонија']],
            ['name' => ['en' => 'Ethiopia', 'mk' => 'Етиопија']],
            ['name' => ['en' => 'Falkland Islands (Malvinas)', 'mk' => 'Фолкландски Острови (Малвински Острови)']],
            ['name' => ['en' => 'Faroe Islands', 'mk' => 'Фарски Острови']],
            ['name' => ['en' => 'Fiji', 'mk' => 'Фиџи']],
            ['name' => ['en' => 'Finland', 'mk' => 'Финска']],
            ['name' => ['en' => 'France', 'mk' => 'Франција']],
            ['name' => ['en' => 'French Guiana', 'mk' => 'Француска Гвајана']],
            ['name' => ['en' => 'French Polynesia', 'mk' => 'Француска Полинезија']],
            ['name' => ['en' => 'Gabon', 'mk' => 'Габон']],
            ['name' => ['en' => 'Gambia', 'mk' => 'Гамбија']],
            ['name' => ['en' => 'Georgia', 'mk' => 'Грузија']],
            ['name' => ['en' => 'Germany', 'mk' => 'Германија']],
            ['name' => ['en' => 'Ghana', 'mk' => 'Гана']],
            ['name' => ['en' => 'Gibraltar', 'mk' => 'Гибралтар']],
            ['name' => ['en' => 'Greece', 'mk' => 'Грција']],
            ['name' => ['en' => 'Greenland', 'mk' => 'Гренланд']],
            ['name' => ['en' => 'Grenada', 'mk' => 'Гренада']],
            ['name' => ['en' => 'Guadeloupe', 'mk' => 'Гвадалупе']],
            ['name' => ['en' => 'Guam', 'mk' => 'Гуам']],
            ['name' => ['en' => 'Guatemala', 'mk' => 'Гватемала']],
            ['name' => ['en' => 'Guernsey', 'mk' => 'Гернзи']],
            ['name' => ['en' => 'Guinea', 'mk' => 'Гвинеја']],
            ['name' => ['en' => 'Guinea-Bissau', 'mk' => 'Гвинеја-Бисау']],
            ['name' => ['en' => 'Guyana', 'mk' => 'Гвајана']],
            ['name' => ['en' => 'Haiti', 'mk' => 'Хаити']],
            ['name' => ['en' => 'Heard Island and Mcdonald Islands', 'mk' => 'Остров Хард и Острови Мекдоналд']],
            ['name' => ['en' => 'Holy See (Vatican City State)', 'mk' => 'Света Столица (Ватиканска Градска Држава)']],
            ['name' => ['en' => 'Honduras', 'mk' => 'Хондурас']],
            ['name' => ['en' => 'Hong Kong', 'mk' => 'Хонг Конг']],
            ['name' => ['en' => 'Hungary', 'mk' => 'Унгарија']],
            ['name' => ['en' => 'Iceland', 'mk' => 'Исланд']],
            ['name' => ['en' => 'India', 'mk' => 'Индија']],
            ['name' => ['en' => 'Indonesia', 'mk' => 'Индонезија']],
            ['name' => ['en' => 'Iran, Islamic Republic of', 'mk' => 'Иран, Исламска Република']],
            ['name' => ['en' => 'Iraq', 'mk' => 'Ирак']],
            ['name' => ['en' => 'Ireland', 'mk' => 'Ирска']],
            ['name' => ['en' => 'Isle of Man', 'mk' => 'Остров на Човекот']],
            ['name' => ['en' => 'Israel', 'mk' => 'Израел']],
            ['name' => ['en' => 'Italy', 'mk' => 'Италија']],
            ['name' => ['en' => 'Jamaica', 'mk' => 'Јамајка']],
            ['name' => ['en' => 'Japan', 'mk' => 'Јапонија']],
            ['name' => ['en' => 'Jersey', 'mk' => 'Џерси']],
            ['name' => ['en' => 'Jordan', 'mk' => 'Јордан']],
            ['name' => ['en' => 'Kazakhstan', 'mk' => 'Казахстан']],
            ['name' => ['en' => 'Kenya', 'mk' => 'Кенија']],
            ['name' => ['en' => 'Kiribati', 'mk' => 'Кирибати']],
            ['name' => ['en' => 'Korea, Democratic People\'s Republic of', 'mk' => 'Кореја, Демократска Народна Република']],
            ['name' => ['en' => 'Korea, Republic of', 'mk' => 'Кореја, Република']],
            ['name' => ['en' => 'Kuwait', 'mk' => 'Кувајт']],
            ['name' => ['en' => 'Kyrgyzstan', 'mk' => 'Киргистан']],
            ['name' => ['en' => 'Lao People\'s Democratic Republic', 'mk' => 'Лаос, Народна Демократска Република']],
            ['name' => ['en' => 'Latvia', 'mk' => 'Летонија']],
            ['name' => ['en' => 'Lebanon', 'mk' => 'Либан']],
            ['name' => ['en' => 'Lesotho', 'mk' => 'Лесото']],
            ['name' => ['en' => 'Liberia', 'mk' => 'Либерија']],
            ['name' => ['en' => 'Libyan Arab Jamahiriya', 'mk' => 'Либиски Арап Џамахирија']],
            ['name' => ['en' => 'Liechtenstein', 'mk' => 'Лихтенштајн']],
            ['name' => ['en' => 'Lithuania', 'mk' => 'Литванија']],
            ['name' => ['en' => 'Luxembourg', 'mk' => 'Луксембург']],
            ['name' => ['en' => 'Macao', 'mk' => 'Макао']],
            ['name' => ['en' => 'Macedonia', 'mk' => 'Македонија']],
            ['name' => ['en' => 'Madagascar', 'mk' => 'Мадагаскар']],
            ['name' => ['en' => 'Malawi', 'mk' => 'Малави']],
            ['name' => ['en' => 'Malaysia', 'mk' => 'Малезија']],
            ['name' => ['en' => 'Maldives', 'mk' => 'Малдиви']],
            ['name' => ['en' => 'Mali', 'mk' => 'Мали']],
            ['name' => ['en' => 'Malta', 'mk' => 'Малта']],
            ['name' => ['en' => 'Marshall Islands', 'mk' => 'Маршалски Острови']],
            ['name' => ['en' => 'Martinique', 'mk' => 'Мартиник']],
            ['name' => ['en' => 'Mauritania', 'mk' => 'Мавританија']],
            ['name' => ['en' => 'Mauritius', 'mk' => 'Маврициус']],
            ['name' => ['en' => 'Mayotte', 'mk' => 'Мајоте']],
            ['name' => ['en' => 'Mexico', 'mk' => 'Мексико']],
            ['name' => ['en' => 'Micronesia, Federated States of', 'mk' => 'Микронезија, Федерални Држави']],
            ['name' => ['en' => 'Moldova, Republic of', 'mk' => 'Молдавија, Република']],
            ['name' => ['en' => 'Monaco', 'mk' => 'Монако']],
            ['name' => ['en' => 'Mongolia', 'mk' => 'Монголија']],
            ['name' => ['en' => 'Montenegro', 'mk' => 'Црна Гора']],
            ['name' => ['en' => 'Montserrat', 'mk' => 'Монсерат']],
            ['name' => ['en' => 'Morocco', 'mk' => 'Мароко']],
            ['name' => ['en' => 'Mozambique', 'mk' => 'Мозамбик']],
            ['name' => ['en' => 'Myanmar', 'mk' => 'Мјанмар']],
            ['name' => ['en' => 'Namibia', 'mk' => 'Намибија']],
            ['name' => ['en' => 'Nauru', 'mk' => 'Науру']],
            ['name' => ['en' => 'Nepal', 'mk' => 'Непал']],
            ['name' => ['en' => 'Netherlands', 'mk' => 'Холандија']],
            ['name' => ['en' => 'New Caledonia', 'mk' => 'Нова Каледонија']],
            ['name' => ['en' => 'New Zealand', 'mk' => 'Нов Зеланд']],
            ['name' => ['en' => 'Nicaragua', 'mk' => 'Никарагва']],
            ['name' => ['en' => 'Niger', 'mk' => 'Нигер']],
            ['name' => ['en' => 'Nigeria', 'mk' => 'Нигерија']],
            ['name' => ['en' => 'Niue', 'mk' => 'Ниуе']],
            ['name' => ['en' => 'Norfolk Island', 'mk' => 'Остров Норфолк']],
            ['name' => ['en' => 'Northern Mariana Islands', 'mk' => 'Северни Маријански Острови']],
            ['name' => ['en' => 'Norway', 'mk' => 'Норвешка']],
            ['name' => ['en' => 'Oman', 'mk' => 'Оман']],
            ['name' => ['en' => 'Pakistan', 'mk' => 'Пакистан']],
            ['name' => ['en' => 'Palau', 'mk' => 'Палау']],
            ['name' => ['en' => 'Palestinian Territory, Occupied', 'mk' => 'Палестинска територија, окупирана']],
            ['name' => ['en' => 'Panama', 'mk' => 'Панама']],
            ['name' => ['en' => 'Papua New Guinea', 'mk' => 'Папуа Нова Гвинеја']],
            ['name' => ['en' => 'Paraguay', 'mk' => 'Парагвај']],
            ['name' => ['en' => 'Peru', 'mk' => 'Перу']],
            ['name' => ['en' => 'Philippines', 'mk' => 'Филипини']],
            ['name' => ['en' => 'Pitcairn', 'mk' => 'Питкерн']],
            ['name' => ['en' => 'Poland', 'mk' => 'Полска']],
            ['name' => ['en' => 'Portugal', 'mk' => 'Португалија']],
            ['name' => ['en' => 'Puerto Rico', 'mk' => 'Порторико']],
            ['name' => ['en' => 'Qatar', 'mk' => 'Катар']],
            ['name' => ['en' => 'Réunion', 'mk' => 'Реунион']],
            ['name' => ['en' => 'Romania', 'mk' => 'Романија']],
            ['name' => ['en' => 'Russian Federation', 'mk' => 'Руска Федерација']],
            ['name' => ['en' => 'Rwanda', 'mk' => 'Руанда']],
            ['name' => ['en' => 'Saint Barthélemy', 'mk' => 'Свети Бартоломеј']],
            ['name' => ['en' => 'Saint Helena, Ascension and Tristan Da Cunha', 'mk' => 'Света Елена, Вознесение и Тристан Да Куња']],
            ['name' => ['en' => 'Saint Kitts and Nevis', 'mk' => 'Сент Китс и Невис']],
            ['name' => ['en' => 'Saint Lucia', 'mk' => 'Света Луција']],
            ['name' => ['en' => 'Saint Martin', 'mk' => 'Свети Мартин']],
            ['name' => ['en' => 'Saint Pierre and Miquelon', 'mk' => 'Свети Пјер и Микелон']],
            ['name' => ['en' => 'Saint Vincent and the Grenadines', 'mk' => 'Сент Винсент и Гренадините']],
            ['name' => ['en' => 'Samoa', 'mk' => 'Самоа']],
            ['name' => ['en' => 'San Marino', 'mk' => 'Сан Марино']],
            ['name' => ['en' => 'Sao Tome and Principe', 'mk' => 'Сао Томе и Принсипе']],
            ['name' => ['en' => 'Saudi Arabia', 'mk' => 'Саудиска Арабија']],
            ['name' => ['en' => 'Senegal', 'mk' => 'Сенегал']],
            ['name' => ['en' => 'Serbia', 'mk' => 'Србија']],
            ['name' => ['en' => 'Seychelles', 'mk' => 'Сејшели']],
            ['name' => ['en' => 'Sierra Leone', 'mk' => 'Сиера Леоне']],
            ['name' => ['en' => 'Singapore', 'mk' => 'Сингапур']],
            ['name' => ['en' => 'Sint Maarten', 'mk' => 'Синт Мартен']],
            ['name' => ['en' => 'Slovakia', 'mk' => 'Словачка']],
            ['name' => ['en' => 'Slovenia', 'mk' => 'Словенија']],
            ['name' => ['en' => 'Solomon Islands', 'mk' => 'Соломонски Острови']],
            ['name' => ['en' => 'Somalia', 'mk' => 'Сомалија']],
            ['name' => ['en' => 'South Africa', 'mk' => 'Јужна Африка']],
            ['name' => ['en' => 'South Georgia and the South Sandwich Islands', 'mk' => 'Јужна Џорџија и Јужни Сендвич Острови']],
            ['name' => ['en' => 'South Sudan', 'mk' => 'Јужен Судан']],
            ['name' => ['en' => 'Spain', 'mk' => 'Шпанија']],
            ['name' => ['en' => 'Sri Lanka', 'mk' => 'Шри Ланка']],
            ['name' => ['en' => 'Sudan', 'mk' => 'Судан']],
            ['name' => ['en' => 'Suriname', 'mk' => 'Суринам']],
            ['name' => ['en' => 'Svalbard and Jan Mayen', 'mk' => 'Свалбард и Јан Мајен']],
            ['name' => ['en' => 'Swaziland', 'mk' => 'Свазиленд']],
            ['name' => ['en' => 'Sweden', 'mk' => 'Шведска']],
            ['name' => ['en' => 'Switzerland', 'mk' => 'Швајцарија']],
            ['name' => ['en' => 'Syrian Arab Republic', 'mk' => 'Сириска Арапска Република']],
            ['name' => ['en' => 'Taiwan, Province of China', 'mk' => 'Тајван, провинција на Кина']],
            ['name' => ['en' => 'Tajikistan', 'mk' => 'Таџикистан']],
            ['name' => ['en' => 'Tanzania, United Republic of', 'mk' => 'Танзанија, Обединета Република']],
            ['name' => ['en' => 'Thailand', 'mk' => 'Тајланд']],
            ['name' => ['en' => 'Timor-Leste', 'mk' => 'Источен Тимор']],
            ['name' => ['en' => 'Togo', 'mk' => 'Того']],
            ['name' => ['en' => 'Tokelau', 'mk' => 'Токелау']],
            ['name' => ['en' => 'Tonga', 'mk' => 'Тонга']],
            ['name' => ['en' => 'Trinidad and Tobago', 'mk' => 'Тринидад и Тобаго']],
            ['name' => ['en' => 'Tunisia', 'mk' => 'Тунис']],
            ['name' => ['en' => 'Turkey', 'mk' => 'Турција']],
            ['name' => ['en' => 'Turkmenistan', 'mk' => 'Туркменистан']],
            ['name' => ['en' => 'Turks and Caicos Islands', 'mk' => 'Острови Туркс и Каикос']],
            ['name' => ['en' => 'Tuvalu', 'mk' => 'Тувалу']],
            ['name' => ['en' => 'Uganda', 'mk' => 'Уганда']],
            ['name' => ['en' => 'Ukraine', 'mk' => 'Украина']],
            ['name' => ['en' => 'United Arab Emirates', 'mk' => 'Обединети Арапски Емирати']],
            ['name' => ['en' => 'United Kingdom', 'mk' => 'Обединето Кралство']],
            ['name' => ['en' => 'United States', 'mk' => 'Соединети Американски Држави']],
            ['name' => ['en' => 'Uruguay', 'mk' => 'Уругвај']],
            ['name' => ['en' => 'Uzbekistan', 'mk' => 'Узбекистан']],
            ['name' => ['en' => 'Vanuatu', 'mk' => 'Вануату']],
            ['name' => ['en' => 'Venezuela, Bolivarian Republic of', 'mk' => 'Венецуела, Боливарска Република']],
            ['name' => ['en' => 'Viet Nam', 'mk' => 'Виетнам']],
            ['name' => ['en' => 'Western Sahara', 'mk' => 'Западна Сахара']],
            ['name' => ['en' => 'Yemen', 'mk' => 'Јемен']],
            ['name' => ['en' => 'Zambia', 'mk' => 'Замбија']],
            ['name' => ['en' => 'Zimbabwe', 'mk' => 'Зимбабве']],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
